services:
  database:
    container_name: database
    restart: unless-stopped
    env_file: .env
    image: postgres:16
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${ADMINUSER}']
    environment:
      POSTGRES_USER: ${ADMINUSER}
      POSTGRES_PASSWORD: ${ADMINPASSWORD}
      POSTGRES_DB: ${STRAPIDATABASENAME}
    volumes:
      - cms-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - strapi

  init-database:
    container_name: init-database
    build:
      dockerfile: Dockerfile.database
      context: .
    env_file: .env
    environment:
      ADMINUSER: ${ADMINUSER}
      ADMINPASSWORD: ${ADMINPASSWORD}
      SERVER: database
      STRAPIUSER: ${STRAPIUSER}
      STRAPIPASSWORD: ${STRAPIPASSWORD}
      STRAPIDATABASENAME: ${STRAPIDATABASENAME}
    networks:
      - strapi
    depends_on:
      database:
        condition: service_healthy

volumes:
  cms-data:

networks:
  strapi:
    name: strapi
    driver: bridge
