name: CI/CD workflow
run-name: ${{ github.actor }} is deploying the cms

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  issues: write
  packages: write
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI/CD
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/cms
          file: ./Dockerfile.prod
          build-args: |
            NODE_ENV=production
