name: PR workflow
run-name: ${{ github.actor }} is building the cms

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write
jobs:
  ci:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    name: CI
    if: github.event.action != 'closed'
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 11

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/cms:${{ env.GITHUB_REF_NAME_SLUG }}
          file: ./Dockerfile.prod
          build-args: |
            NODE_ENV=production

